# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_favori_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favori',
            name='comment',
            field=models.TextField(max_length=512),
        ),
    ]
